/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/brighthouse/brighthouse.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[-1.93, 0, 2.25]}>
        <group position={[1.93, 0, -2.25]}>
          <mesh geometry={nodes.Window_1.geometry} material={materials.PVC} />
          <mesh geometry={nodes.Window_2.geometry} material={materials.Plastic} />
          <mesh geometry={nodes.Window_3.geometry} material={materials['gltf glass']} />
          <mesh geometry={nodes.Window_4.geometry} material={materials['Marble.001']} />
        </group>
      </group>
      <group position={[-4.23, 0, 0]} rotation={[0, 1.57, 0]}>
        <group position={[4.23, 0, 0]}>
          <mesh geometry={nodes.Window001_1.geometry} material={materials.PVC} />
          <mesh geometry={nodes.Window001_2.geometry} material={materials.Plastic} />
          <mesh geometry={nodes.Window001_3.geometry} material={materials['gltf glass']} />
          <mesh geometry={nodes.Window001_4.geometry} material={materials['Marble.001']} />
        </group>
      </group>
      <group position={[4.69, 0, 5.41]} rotation={[0, 1.57, 0]}>
        <group position={[-4.69, 0, -5.05]}>
          <mesh geometry={nodes.Window004_1.geometry} material={materials.PVC} />
          <mesh geometry={nodes.Window004_2.geometry} material={materials.Plastic} />
          <mesh geometry={nodes.Window004_3.geometry} material={materials['gltf glass']} />
          <mesh geometry={nodes.Window004_4.geometry} material={materials['Marble.001']} />
        </group>
      </group>
      <group position={[1.66, 3.05, 2.31]}>
        <group position={[-1.66, -3.05, -2.31]}>
          <mesh geometry={nodes.Window002_1.geometry} material={materials.PVC} />
          <mesh geometry={nodes.Window002_2.geometry} material={materials.Plastic} />
          <mesh geometry={nodes.Window002_3.geometry} material={materials['gltf glass']} />
          <mesh geometry={nodes.Window002_4.geometry} material={materials['Marble.001']} />
        </group>
      </group>
      <group position={[-0.93, 3.05, 0.03]} rotation={[0, 1.57, 0]}>
        <group position={[0.93, -3.05, -0.03]}>
          <mesh geometry={nodes.Window003_1.geometry} material={materials.PVC} />
          <mesh geometry={nodes.Window003_2.geometry} material={materials.Plastic} />
          <mesh geometry={nodes.Window003_3.geometry} material={materials['gltf glass']} />
          <mesh geometry={nodes.Window003_4.geometry} material={materials['Marble.001']} />
        </group>
      </group>
      <group position={[-1.93, 0.37, -0.28]} scale={[0.76, 0.55, 0.76]}>
        <mesh geometry={nodes.Cube011.geometry} material={materials['Wood Table ']} position={[0, 0.02, 0]} scale={[0.9, 1.24, 0.9]} />
        <mesh geometry={nodes.Cube018.geometry} material={materials['Concrete Leg']} position={[-0.72, -0.01, -0.41]} scale={[0.9, 1.24, 0.9]} />
        <mesh geometry={nodes.Cube019.geometry} material={materials['Concrete Leg']} position={[-0.72, -0.01, 0.41]} rotation={[0, 1.57, 0]} scale={[0.9, 1.24, 0.9]} />
        <mesh geometry={nodes.Cube020.geometry} material={materials['Concrete Leg']} position={[0.72, -0.01, -0.41]} rotation={[Math.PI, -1.57, 0]} scale={[-0.9, -1.24, -0.9]} />
        <mesh geometry={nodes.Cube021.geometry} material={materials['Concrete Leg']} position={[0.72, -0.01, 0.41]} rotation={[0, 0, -Math.PI]} scale={[-0.9, -1.24, -0.9]} />
      </group>
      <group position={[-0.32, 0, -1.82]} scale={0.54}>
        <mesh geometry={nodes.Circle006.geometry} material={materials['Glossy Black']} scale={0.39} />
        <mesh geometry={nodes.Cylinder.geometry} material={materials['Material.002']} position={[-0.02, 2.44, 0]} scale={[0.33, 0.21, 0.33]} />
        <mesh geometry={nodes.Cylinder001.geometry} material={nodes.Cylinder001.material} position={[-0.02, 2.55, 0]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.03, 0.31, 0.03]} />
      </group>
      <group position={[3.93, 3.04, -1.93]} scale={0.54}>
        <mesh geometry={nodes.Circle007.geometry} material={materials['Glossy Black']} scale={0.39} />
        <mesh geometry={nodes.Cylinder002.geometry} material={materials['Material.002']} position={[-0.02, 2.44, 0]} scale={[0.33, 0.21, 0.33]} />
        <mesh geometry={nodes.Cylinder003.geometry} material={nodes.Cylinder003.material} position={[-0.02, 2.55, 0]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.03, 0.31, 0.03]} />
      </group>
      <group position={[-0.33, 0, -1.22]} scale={0.31}>
        <group scale={1.25}>
          <mesh geometry={nodes.Cube009.geometry} material={materials['Bush Bark']} />
          <mesh geometry={nodes.Cube009_1.geometry} material={materials.TexturesCom_Leaves0126_1_alphamasked_S} />
        </group>
        <mesh geometry={nodes.Cylinder004.geometry} material={materials.Pot} position={[0, 0.13, 0]} scale={0.14} />
      </group>
      <mesh geometry={nodes.Plane.geometry} material={materials['Dirty Concrete']} />
      <mesh geometry={nodes.Plane_1.geometry} material={materials.Tiles} />
      <mesh geometry={nodes.Plane_2.geometry} material={materials.Dirt} />
      <mesh geometry={nodes.Plane_3.geometry} material={materials['Grassy Concrete']} />
      <mesh geometry={nodes.Cube004.geometry} material={materials.Bricks} />
      <mesh geometry={nodes.Cube004_1.geometry} material={materials['Clean Concrete']} />
      <mesh geometry={nodes.Cube004_2.geometry} material={materials.Dirt} />
      <mesh geometry={nodes.pool_water.geometry} material={materials['gltf water']} />
      <mesh geometry={nodes.Circle.geometry} material={materials['Concrete Wall']} position={[0.03, -0.22, 6.48]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Circle001.geometry} material={materials['Concrete Wall']} position={[-2.79, -0.22, 6.48]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Circle002.geometry} material={materials['Concrete Wall']} position={[2.94, -0.22, 6.48]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Circle003.geometry} material={materials['Concrete Wall']} position={[0.09, -0.22, 6.24]} rotation={[Math.PI / 2, 0, -Math.PI]} />
      <mesh geometry={nodes.Circle004.geometry} material={materials['Concrete Wall']} position={[2.9, -0.22, 6.24]} rotation={[Math.PI / 2, 0, -Math.PI]} />
      <mesh geometry={nodes.Circle005.geometry} material={materials['Concrete Wall']} position={[-2.82, -0.22, 6.24]} rotation={[Math.PI / 2, 0, -Math.PI]} />
      <mesh geometry={nodes.Cube_1.geometry} material={materials['Concrete Wall']} />
      <mesh geometry={nodes.Cube_2.geometry} material={materials['Outer Concrete Wall']} />
      <mesh geometry={nodes.home_lower_floor.geometry} material={materials['Concrete Floor']} />
      <mesh geometry={nodes.home_rail_back.geometry} material={materials['gltf glass']} position={[-2.61, 3.53, -2.22]} rotation={[Math.PI / 2, 0, 0]} scale={[0.99, 1, 1]} />
      <mesh geometry={nodes.home_rail_front.geometry} material={materials['gltf glass']} position={[-2.61, 3.53, 2.3]} rotation={[Math.PI / 2, 0, 0]} scale={[0.99, 1, 1]} />
      <mesh geometry={nodes.Cube003.geometry} material={materials['Clean Concrete']} />
      <mesh geometry={nodes.Cube003_1.geometry} material={materials['White Glossy']} />
      <mesh geometry={nodes.Cube003_2.geometry} material={materials['Concrete Floor']} />
      <mesh geometry={nodes.Cube003_3.geometry} material={materials['Concrete Wall']} />
      <mesh geometry={nodes.Cube003_4.geometry} material={materials['Outer Concrete Wall']} />
      <mesh geometry={nodes.Cube001_1.geometry} material={materials['White Glossy']} />
      <mesh geometry={nodes.Cube001_2.geometry} material={materials['Concrete Floor']} />
      <mesh geometry={nodes.sand.geometry} material={materials.Sand} position={[0, -0.03, 0]} scale={76.88} />
      <mesh geometry={nodes.statue.geometry} material={materials.resting_nude_opti} position={[1.55, 3.42, 0]} rotation={[Math.PI / 2, 0, -1.64]} scale={0} />
      <mesh geometry={nodes.sofa.geometry} material={materials.Sofa} position={[-3.58, 0.04, 0.72]} scale={0.58} />
      <mesh geometry={nodes.pillow1.geometry} material={materials['Material.003']} position={[-3.53, 0.49, -1.81]} rotation={[0.72, -0.02, 0.04]} scale={[0.29, 0.06, 0.25]} />
      <mesh geometry={nodes.pillow2.geometry} material={materials['Material.002']} position={[-3.86, 0.56, -1.54]} rotation={[0, 0, -1.28]} scale={[0.29, 0.06, 0.25]} />
      <mesh geometry={nodes.pillow3.geometry} material={materials['Material.003']} position={[-1.12, 0.52, -1.83]} rotation={[Math.PI, -1.18, 2.13]} scale={[0.29, 0.06, 0.25]} />
      <mesh geometry={nodes.pillow4.geometry} material={materials['Material.002']} position={[-0.97, 0.52, -1.47]} rotation={[3.03, -0.19, 2.38]} scale={[0.29, 0.06, 0.25]} />
      <mesh geometry={nodes.pillow5.geometry} material={materials['Material.004']} position={[-3.78, 0.54, -1.17]} rotation={[0, -0.39, -0.97]} scale={[0.29, 0.06, 0.25]} />
      <mesh geometry={nodes.Plane001.geometry} material={materials['Wood Table ']} position={[5.24, 3.03, -1.23]} />
      <mesh geometry={nodes.Modern_Staircase.geometry} material={materials['Wood Table ']} position={[6.58, 0.14, 2.81]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={0.9} />
      <mesh geometry={nodes.home_rail_front002.geometry} material={materials['gltf glass']} position={[5.16, 3.27, -1.28]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[0.54, 0.55, 0.55]} />
      <mesh geometry={nodes.home_rail_front001.geometry} material={materials['gltf glass']} position={[5.66, 2.03, 2.82]} rotation={[Math.PI / 2, 0, 0]} scale={[0.54, 0.55, 0.55]} />
      <mesh geometry={nodes.Cylinder005.geometry} material={materials.Marble} position={[6.19, 0.49, 9.32]} scale={0.5} />
      <mesh geometry={nodes.vines.geometry} material={materials.wood_seamless2} position={[6.65, 0.52, 8.84]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.11} />
      <group position={[6.42, 1.19, 9.28]} rotation={[0, -1.32, 0]} scale={[0.13, 0.2, 0.13]}>
        <mesh geometry={nodes.Cube006.geometry} material={materials.Speaker} />
        <mesh geometry={nodes.Cube006_1.geometry} material={materials.Plastic} />
        <mesh geometry={nodes.Cube006_2.geometry} material={materials['Speaker 2']} />
      </group>
      <group position={[6.02, 1.12, 9.3]} rotation={[Math.PI / 2, 0, 1.91]} scale={[0.13, 0.2, 0.13]}>
        <mesh geometry={nodes.Cube005.geometry} material={materials.Speaker} />
        <mesh geometry={nodes.Cube005_1.geometry} material={materials['Speaker 2']} />
        <mesh geometry={nodes.Cube005_2.geometry} material={materials.Plastic} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/brighthouse/brighthouse.gltf')
